e2e/ci: switch to httpie using correct auth flag

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -70,7 +70,7 @@ jobs:
       - name: Check mock supervisor log
         run: cat mock_supervisor.log
       - name: Run E2E API tests
-        run: "# Set up variables\ntml_supervisor=\"7d55ec6d-15e7-4b84-8c04-7c085fe60df4\"\ntml_image_id=\"46ebc6946f7c4a10922bf1f539cd7351ce8670781e081d18babf1affdef6f577\"\ntml_token=\"B1oy2ko1wVdGKbvKc/9dKi7ggZYLTLzdm2As4CWV15fyuzvHsbBQOvnN+/RpB7OvVJjRYhldlSY4iFsNZq5XpO8fXiqRN6O/gn+nP5cA1J6ox2d2jV32TGzahTZAQZUFwIsI11Mye+Jus97L1e+l3O/0yBt/sywoJFFwkUVOFX8\"\n\necho \"Using pre-defined token: $tml_token\"\n\n# Create a job\necho \"Sending job creation request...\"\njob_response=$(http --print=b -A bearer -a \"${tml_token}\" POST localhost:8080/api/v1/job/queue \\\n  supervisor_id=\"${tml_supervisor}\" \\\n  job_request[request_id]=\"$(uuidgen)\" \\\n  job_request[init_spec][type]=image \\\n  job_request[init_spec][image_id]=\"${tml_image_id}\" \\\n  job_request[ssh_keys]:='[]' \\\n  job_request[restart_policy][remaining_restart_count]:=0 \\\n  job_request[ssh_rendezvous_servers]:='[]' \\\n  job_request[parameters]:='{}' \\\n  job_request[tag_config]='' \\\n  job_request[override_timeout]:=null)\n\necho \"Create job response: $job_response\"\n\njob_id=$(echo \"$job_response\" | jq -r '.job_id // empty')\n\nif [ -z \"$job_id\" ]; then\n  echo \"Failed to create job\"\n  exit 1\nfi\n\necho \"Created job with ID: $job_id\"\n\n# Wait for the job to start (you might need to adjust the sleep time)\nsleep 10\n\n# Check job status\nstatus_response=$(http --print=b -A bearer -a \"${tml_token}\" GET localhost:8080/api/v1/job/${job_id}/status)\n\necho \"Status response: $status_response\"\n\njob_status=$(echo \"$status_response\" | jq -r '.state // empty')\n\necho \"Job status: $job_status\"\n\n# Cancel the job\ncancel_response=$(http --print=b -A bearer -a \"${tml_token}\" DELETE localhost:8080/api/v1/job/${job_id})\n\necho \"Cancel response: $cancel_response\"\necho \"Cancelled job\"\n\n# Check job status again\nstatus_response=$(http --print=b -A bearer -a \"${tml_token}\" GET localhost:8080/api/v1/job/${job_id}/status)\n\necho \"Status response after cancellation: $status_response\"\n\njob_status=$(echo \"$status_response\" | jq -r '.state // empty')\n\necho \"Job status after cancellation: $job_status\"\n\n# Verify the job was cancelled\nif [ \"$job_status\" != \"Cancelled\" ]; then\n  echo \"Job was not cancelled successfully\"\n  exit 1\nfi\n\necho \"E2E API test completed successfully\"      \n"
+        run: "# Set up variables\ntml_supervisor=\"7d55ec6d-15e7-4b84-8c04-7c085fe60df4\"\ntml_image_id=\"46ebc6946f7c4a10922bf1f539cd7351ce8670781e081d18babf1affdef6f577\"\ntml_token=\"B1oy2ko1wVdGKbvKc/9dKi7ggZYLTLzdm2As4CWV15fyuzvHsbBQOvnN+/RpB7OvVJjRYhldlSY4iFsNZq5XpO8fXiqRN6O/gn+nP5cA1J6ox2d2jV32TGzahTZAQZUFwIsI11Mye+Jus97L1e+l3O/0yBt/sywoJFFwkUVOFX8\"\n\necho \"Using pre-defined token: $tml_token\"\n\n# Create a job\necho \"Sending job creation request...\"\njob_response=$(http --print=b -H \"Authorization: Bearer ${tml_token}\" POST localhost:8080/api/v1/job/queue \\\n  supervisor_id=\"${tml_supervisor}\" \\\n  job_request[request_id]=\"$(uuidgen)\" \\\n  job_request[init_spec][type]=image \\\n  job_request[init_spec][image_id]=\"${tml_image_id}\" \\\n  job_request[ssh_keys]:='[]' \\\n  job_request[restart_policy][remaining_restart_count]:=0 \\\n  job_request[ssh_rendezvous_servers]:='[]' \\\n  job_request[parameters]:='{}' \\\n  job_request[tag_config]='' \\\n  job_request[override_timeout]:=null)\n\necho \"Create job response: $job_response\"\n\njob_id=$(echo \"$job_response\" | jq -r '.job_id // empty')\n\nif [ -z \"$job_id\" ]; then\n  echo \"Failed to create job\"\n  exit 1\nfi\n\necho \"Created job with ID: $job_id\"\n\n# Wait for the job to start (you might need to adjust the sleep time)\nsleep 10\n\n# Check job status\nstatus_response=$(http --print=b -H \"Authorization: Bearer ${tml_token}\" GET localhost:8080/api/v1/job/${job_id}/status)\n\necho \"Status response: $status_response\"\n\njob_status=$(echo \"$status_response\" | jq -r '.state // empty')\n\necho \"Job status: $job_status\"\n\n# Cancel the job\ncancel_response=$(http --print=b -H \"Authorization: Bearer ${tml_token}\" DELETE localhost:8080/api/v1/job/${job_id})\n\necho \"Cancel response: $cancel_response\"\necho \"Cancelled job\"\n\n# Check job status again\nstatus_response=$(http --print=b -H \"Authorization: Bearer ${tml_token}\" GET localhost:8080/api/v1/job/${job_id}/status)\n\necho \"Status response after cancellation: $status_response\"\n\njob_status=$(echo \"$status_response\" | jq -r '.state // empty')\n\necho \"Job status after cancellation: $job_status\"\n\n# Verify the job was cancelled\nif [ \"$job_status\" != \"Cancelled\" ]; then\n  echo \"Job was not cancelled successfully\"\n  exit 1\nfi\n\necho \"E2E API test completed successfully\"      \n"
       - name: Run database interaction tests
         run: |
           echo "TODO"
