added attempting second request after first

diff --git a/.github/workflows/e2e-tests.yml b/.github/workflows/e2e-tests.yml
--- a/.github/workflows/e2e-tests.yml
+++ b/.github/workflows/e2e-tests.yml
@@ -66,13 +66,13 @@ jobs:
           export RUST_LOG=debug
           cargo run --package tml-switchboard -- serve -c switchboard_config.toml > switchboard.log 2>&1 &
           echo $! > switchboard.pid
-          sleep 5
+          sleep 1
       - name: Start mock supervisor
         run: |
           cargo build --package tml-puppet
           nohup cargo run --package tml-mock-supervisor -- -c mock_supervisor_config.toml --puppet-binary ./target/debug/tml-puppet > mock_supervisor.log 2>&1 &
           echo $! > mock_supervisor.pid
-          sleep 5
+          sleep 1
       - name: Check mock supervisor log
         run: cat mock_supervisor.log
       - name: Check for supervisor panic
@@ -127,7 +127,7 @@ jobs:
 
           echo "Created job with ID: $job_id"
 
-          sleep 10
+          sleep 1
 
           echo "Checking job status..."
           if ! status_response=$(http --check-status --ignore-stdin --timeout=10 --print=b -A bearer -a "${tml_token}" GET localhost:8080/api/v1/job/${job_id}/status)
@@ -141,14 +141,13 @@ jobs:
 
           echo "Job status before cancellation: $job_status"
 
-          echo "Cancelling job..."
+          echo "Cancelling job 1 ..."
           if ! cancel_response=$(http --check-status --ignore-stdin --timeout=10 --print=b -A bearer -a "${tml_token}" DELETE localhost:8080/api/v1/job/${job_id})
           then
             handle_http_error $?
           fi
 
           echo "Cancel response: $cancel_response"
-          echo "Cancelled job"
 
           echo "Checking job status after cancellation..."
           if ! status_response=$(http --check-status --ignore-stdin --timeout=10 --print=b -A bearer -a "${tml_token}" GET localhost:8080/api/v1/job/${job_id}/status)
@@ -161,6 +160,57 @@ jobs:
           job_status=$(echo "$status_response" | jq -r '.job_status.job_status.job_state.state // empty')
 
           echo "Job status after cancellation: $job_status"
+
+          # Verify the job was cancelled (checking for "finished" state)
+          if [ "$job_status" != "finished" ]; then
+            echo "Job was not cancelled successfully"
+            exit 1
+          fi
+
+          echo "Sending second job creation request..."
+          job_response=$(http --check-status --ignore-stdin --timeout=10 --print=b -A bearer -a "${tml_token}" POST localhost:8080/api/v1/job/queue \
+            supervisor_id="${tml_supervisor}" \
+            job_request[request_id]="$(uuidgen)" \
+            job_request[init_spec][type]=image \
+            job_request[init_spec][image_id]="${tml_image_id}" \
+            job_request[ssh_keys]:='[]' \
+            job_request[restart_policy][remaining_restart_count]:=0 \
+            job_request[ssh_rendezvous_servers]:='[]' \
+            job_request[parameters]:='{}' \
+            job_request[tag_config]='' \
+            job_request[override_timeout]:=null) || handle_http_error $?
+
+          echo "Create second job response: $job_response"
+
+          job_id=$(echo "$job_response" | jq -r '.job_id // empty')
+
+          if [ -z "$job_id" ]; then
+            echo "Failed to extract job ID from second response"
+            exit 1
+          fi
+
+          echo "Second Job status before cancellation: $job_status"
+
+
+          echo "Cancelling job 2 ..."
+          if ! cancel_response=$(http --check-status --ignore-stdin --timeout=10 --print=b -A bearer -a "${tml_token}" DELETE localhost:8080/api/v1/job/${job_id})
+          then
+            handle_http_error $?
+          fi
+
+          echo "Cancel response 2: $cancel_response"
+
+          echo "Checking second job status after cancellation..."
+          if ! status_response=$(http --check-status --ignore-stdin --timeout=10 --print=b -A bearer -a "${tml_token}" GET localhost:8080/api/v1/job/${job_id}/status)
+          then
+            handle_http_error $?
+          fi
+
+          echo "Status response after cancellation: $status_response"
+
+          job_status=$(echo "$status_response" | jq -r '.job_status.job_status.job_state.state // empty')
+
+          echo "Second Job status after cancellation: $job_status"
 
           # Verify the job was cancelled (checking for "finished" state)
           if [ "$job_status" != "finished" ]; then
